version: '3.7'

services:
  dev_rabbitmq:
    image: rabbitmq:3-management
    container_name: mongorr_rabbitmq
    restart: on-failure
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq_data_volume:/var/lib/rabbitmq/mnesia
      
  dev_redis:
    image: redis
    container_name: mongorr_redis
    restart: on-failure
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"  
    volumes:
      - redis_data_volume:/data

  dev_mongodb:
    image: mongo:latest
    container_name: "mongorr_mongodb"
    environment:
      - MONGODB_USER="user" 
      - MONGODB_PASS="pass"
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongodb_data_volume:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null 
    
  dev_elasticsearch:
    image: elasticsearch:7.7.1
    container_name: "elk_elasticsearch"
    restart: on-failure
    networks:
      - elk
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data_volume:/opt/elasticsearch/data
  

  dev_logstash:
    image: logstash:7.7.1
    container_name: "elk_logstash"
    restart: on-failure
    ports:
      - "24642:24642"
      - "35753:35753"
      - "5044:5044"
    command: -f /usr/share/logstash/config/conf.d/logstash.conf
    tty: true
    privileged: true
    volumes:
      - ./logstash/assets/logstash.conf:/usr/share/logstash/config/conf.d/logstash.conf
      - ./logstash/assets/logstash.yml:/usr/share/logstash/config/logstash.yml
      -  logstash_data_volume:/home/logstash
    links:
      - dev_elasticsearch
    networks:
      - elk
      
  dev_kibana:
    image: kibana:7.7.1
    container_name: "elk_kibana"
    restart: on-failure
    ports: 
       - "5601:5601"
    links:
      - dev_elasticsearch
    networks:
      - elk
    volumes:
      - ./kibana/assets/kibana.yml:/usr/share/kibana/config/kibana.yml 
  dev_nginx:
    image: nginx:stable-alpine
    container_name: "elk_nginx"
    restart: on-failure
    links:
      - dev_kibana
    ports: 
      - "80:80"
      - "443:443"
    networks:
      - elk
    volumes:
      - ./nginx/assets/certs:/etc/nginx/certs
      - ./nginx/assets/nginx.conf:/etc/nginx/nginx.conf


networks:
  elk:
    ipam:
      config:
      - subnet: 127.0.0.1/24

volumes:
  rabbitmq_data_volume:
  redis_data_volume:
  mongodb_data_volume:
  elasticsearch_data_volume:
  logstash_data_volume:
